### ISSUE TITLE
Sorting and Aligning on the visualizations

### ISSUE THREAD

**Issue by rustama** [hackolade/ArangoDB#3]
Attempting to use "Select All" and "Align" features (from Edit Menu) of the Hackolade over Graph or ER Diagram, pretty much not working. Not sure, so, if it is plugin responsibility/effect or the tool itself.

Also not found clear way to sort collections, edges and other elements by lex on the Object Browser.

**Comment by pdesmarets** [comment]
Moving objects up or down in the Object Browser is currently in development.  It will be in the next release, and if not, in the following one.  So, stay tuned.

Alignment of shapes in the diagram is indeed disabled in graph plugins (i.e., indeed for ArangoDB).  This is mainly because of the forced-directed layout.

**Comment by rustama** [comment]
Great News! Thank You
